CREATE DATABASE IF NOT EXISTS grace;

USE grace;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
userID VARCHAR(40),
conditionID INT,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS grace_logs;
CREATE TABLE IF NOT EXISTS grace_logs (
id INT NOT NULL AUTO_INCREMENT,
userID VARCHAR(40),
time BIGINT,
type VARCHAR(60),
data VARCHAR(8000),
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS hoc_logs;
CREATE TABLE IF NOT EXISTS hoc_logs (
id INT NOT NULL AUTO_INCREMENT,
userID VARCHAR(40),
time BIGINT,
type VARCHAR(60),
data VARCHAR(8000),
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS drag_logs;
CREATE TABLE IF NOT EXISTS drag_logs (
id INT NOT NULL AUTO_INCREMENT,
userID VARCHAR(40),
time BIGINT,
type VARCHAR(60),
data VARCHAR(8000),
PRIMARY KEY (id)
);
